"""Initial models

Revision ID: 67812b424c2b
Revises: 
Create Date: 2026-05-18 03:32:51.770137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67812b424c2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('numerator', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('denominator', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action_type IN ('SPLIT', 'BONUS', 'DIVIDEND')", name='chk_action_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', 'action_date', 'action_type', name='uq_corporate_actions')
    )
    op.create_index('idx_corporate_actions_ticker_date', 'corporate_actions', ['ticker', 'action_date'], unique=False)
    op.create_table('raw_corporate_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_type_raw', sa.String(length=100), nullable=False),
    sa.Column('numerator', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('denominator', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_actions_ticker_date', 'raw_corporate_actions', ['ticker', 'action_date'], unique=False)
    op.create_table('raw_dividends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('dividend_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', 'ex_date', name='uq_dividends_ticker_exdate')
    )
    op.create_index('idx_dividends_ticker_exdate', 'raw_dividends', ['ticker', 'ex_date'], unique=False)
    op.create_table('raw_market_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', 'trade_date', name='uq_market_data_ticker_date')
    )
    op.create_index('idx_market_data_ticker_date', 'raw_market_data', ['ticker', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_market_data_ticker_date', table_name='raw_market_data')
    op.drop_table('raw_market_data')
    op.drop_index('idx_dividends_ticker_exdate', table_name='raw_dividends')
    op.drop_table('raw_dividends')
    op.drop_index('idx_raw_actions_ticker_date', table_name='raw_corporate_actions')
    op.drop_table('raw_corporate_actions')
    op.drop_index('idx_corporate_actions_ticker_date', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
